### ISSUE TITLE
possibly not copied some static files?

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/galaxy#1]
I tried the galaxy with fits locally, looks very nice! I think we can make ready. Just one thing, I am not sure, but when I start run.sh it misses script.js and aladin js in static files. I copied them from src/  and it works, but I am not sure why whey were not available while css was. Maybe it's some problem with my instance, but maybe could you make sure it works starting from a fresh clone?

Maybe it's useful if @dsavchenko also checks?

**Comment by francoismg** [comment]
@volodymyrss If I understood correctly Gulp is supposed to copy the files from "plugin"/static to /static and it was working fine but yesterday evening I started to have the same issue with the files not being copied and some older version of the files being used sometimes (like some caching problem). I thought the instance was having some problem (seemed like rebuilding the app too many times could cause issues) but if you are experiencing the same problem it must be something else. It's weird cause everything was working fine until yesterday evening, I will investigate that

**Comment by francoismg** [comment]
@volodymyrss ok I have been able to make it work and dependencies have been automatically copied from plugin/static to /static but there's some really strange and inconsistent behaviors.

Basically if you run "yarn build" from the venv and then "sh run.sh" or "make client" it works. Yarn correctly builds the scripts and move them from plugin/src to plugin/static and then gulp is able to copy them to the /static folder but you shouldn't have to do that since run.sh does it too

Could you try to paste the log (you can stop the script when you see this line GXY_BUILD_SOURCEMAPS=1 NODE_ENV=production webpack) from run.sh (you can use sh run.sh > /dev/null so it will output less noise) please? and also the output from "make client" and check if a "plugin_hash.txt" file has been generated in the /plugin/static folder. Thanks

Also could you give me the node version on your machine? (node -v)

However there are some really strange behaviors happening and I think most of the problems come from the fact that every part seems to be using different dependencies versions with different configurations 

- There's seems to be some differences when you run yarn build yourself and when it's run from the run.sh script. The script seems to install another install of yarn on the fly so there might be some configuration differences between the two (version is the same)
- There's some difference between using "make client" and letting run.sh making the client. When using make client the current node instance is used but when using run.sh it seems to use a prebuilt node (version 18) and strangely that version seem to rely on node file from my node which is version 20 
- When using a node version > 16 gulp will set some specific node options on the fly which causes some errors and seems to stop the generation of the plugin hash file, since the options is set on the fly you cannot modify the configuration however I was able to change the gulpfile so it won't set the option which seemed to solve that problem
-  Sometimes a plugin_hash_file.origin will be created instead of the standard hash file
- The changes that trigger a client rebuild don't seem to be consistent (sometimes it won't rebuild the client and you have to manually delete the hash file and rerun a yarn build)
- There's also seems to be some really strange cache issues, yesterday gabrielle asked me a question about aladin so I ran some tests on the galaxy instance and the url I used for these tests is still present in the script in the browser even tough I have removed that url, made other changes that were incorporated in the script, manually removed the cache files and disabled caching in the browser 
- Also it looks like when running the same build twice you can have different outcomes even without any changes

I will try to find if there's a clean way to make the plugin startup work in a consistent manner

**Comment by volodymyrss** [comment]
I'll paste the logs tomorrow. However, realistically, we may not need to refine this ourselves if this is galaxy behavior. Even though it might be good to figure out a bit on our own.

**Comment by francoismg** [comment]
> I'll paste the logs tomorrow. However, realistically, we may not need to refine this ourselves if this is galaxy behavior. Even though it might be good to figure out a bit on our own.

Thanks. Yes ok maybe we can just let it as is, it's just weird cause it's hard to know if it's a bug, expected behavior, an error I made or something else entirely

**Comment by volodymyrss** [comment]
It does not repeat the same way for me in different laptop. By the way, node is installed, I had none on the laptop I tried yesterday.
Maybe let's just ask it to them, could you just comment in that issue what you descried here, with a comment from my issue here (and a reference to this issue)?

It sounds like like something we should discuss with them.

As for functionality, I think the astronomers will be pretty happy with what's there.

**Comment by francoismg** [comment]
When you say it does not repeat the same way you mean everything is working fine or you get some other things?

Ok sure I can add a comment on the pull request with a reference to this issue no problem

**Comment by volodymyrss** [comment]
> When you say it does not repeat the same way you mean everything is working fine or you get some other things?

It was crashing due to a different reason, but it looks like this depends on python version.

with python 3.9.16 I get the same error as the other platform, the same file missing.

> Ok sure I can add a comment on the pull request with a reference to this issue no problem

They should be able to help.

Maybe we can also prepare clear containerized environment. Also we will be able to run them in EPFL as a dev instance.

**Comment by francoismg** [comment]
ok I think that maybe the error in your case is that you'r missing parcel, I thought it was shipped with galaxy but now I think I might have had to install it myself. You can try to run "npm install parcel-bundler -g" and then remake the client, if that fixes the problem I will just add parcel as a dependency in the package.json and we should be good

I will look into making a container no problem

**Comment by volodymyrss** [comment]
> npm install parcel-bundler -g

Just doing it did not help (it was not added in the right environment it seems) but adding [dependency](https://github.com/esg-epfl-apc/galaxy/commit/66427a9882dfd70ca3a8e2b25aab64c612883a28) works, thanks!

**Comment by francoismg** [comment]
ok great thanks, I will make the changes and push them

**Comment by volodymyrss** [comment]
and then just mark PR ready when you want
